global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape API metrics
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  # Scrape Lokiâ€™s own metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
